# Generated by Django 6.0.4 on 2026-05-21 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_timing', models.IntegerField(default=15)),
                ('overtime_rules', models.CharField(default='Standard', max_length=255)),
                ('leave_carry_forward', models.BooleanField(default=False)),
                ('leave_approvals', models.CharField(default='Manager', max_length=50)),
                ('leave_type_configuration', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'Attendance & Leave Settings',
            },
        ),
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#000000', max_length=50)),
                ('theme_support', models.CharField(default='Light', max_length=50)),
                ('dashboard_widget_toggles', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'Branding Settings',
            },
        ),
        migrations.CreateModel(
            name='ExpenseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_size_limit', models.IntegerField(default=5)),
                ('allowed_file_formats', models.CharField(default='pdf,jpg,png', max_length=255)),
                ('compression_thresholds', models.IntegerField(default=2)),
                ('reimbursement_policies', models.TextField(blank=True, default='')),
                ('approval_hierarchy', models.CharField(default='Manager -> Finance', max_length=50)),
                ('category_management', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'Expense Settings',
            },
        ),
        migrations.CreateModel(
            name='LifecycleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_rules', models.TextField(blank=True, default='')),
                ('offboarding_rules', models.TextField(blank=True, default='')),
                ('employee_id_generation', models.CharField(default='Auto', max_length=50)),
                ('probation_settings', models.IntegerField(default=90)),
                ('asset_return_workflow', models.TextField(blank=True, default='')),
                ('account_disable_logic', models.CharField(default='Immediate', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Lifecycle Settings',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode_enabled', models.BooleanField(default=False)),
                ('cache_clearing_hooks', models.JSONField(default=dict)),
                ('backup_configuration_readiness', models.BooleanField(default=False)),
                ('logging_controls', models.CharField(default='Standard', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Maintenance Settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('task_alerts', models.BooleanField(default=True)),
                ('leave_alerts', models.BooleanField(default=True)),
                ('expense_alerts', models.BooleanField(default=True)),
                ('attendance_alerts', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Company Name', max_length=255)),
                ('official_email', models.EmailField(default='contact@company.com', max_length=254)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('office_timings', models.CharField(default='09:00 AM - 06:00 PM', max_length=255)),
                ('working_days', models.CharField(default='Monday - Friday', max_length=255)),
                ('holidays', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Organization Settings',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_policy', models.CharField(default='Standard', max_length=255)),
                ('session_timeout', models.IntegerField(default=30)),
                ('login_attempt_limit', models.IntegerField(default=5)),
                ('two_factor_auth_enabled', models.BooleanField(default=False)),
                ('device_session_handling', models.CharField(default='Concurrent', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Security Settings',
            },
        ),
        migrations.CreateModel(
            name='SettingsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('field_changes', models.JSONField()),
                ('old_value', models.JSONField()),
                ('new_value', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_statuses', models.JSONField(default=list)),
                ('escalation_rules', models.TextField(blank=True, default='')),
                ('reminder_configuration', models.JSONField(default=dict)),
                ('assignment_rules', models.TextField(blank=True, default='')),
                ('task_priority_labels', models.JSONField(default=list)),
            ],
            options={
                'verbose_name_plural': 'Task Settings',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_module.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='settings_module.role')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
