# Generated by Django 5.2.13 on 2026-05-08 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_employee_team_leader_task_assigned_by_team_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportquery',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportquery',
            name='target_role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
