# Generated by Django 5.2.13 on 2026-05-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_supportquery_recipient_supportquery_target_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='blood_group',
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('intern', 'Intern')], default='employee', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift')], default='day', max_length=20),
        ),
    ]
