# Generated by Django 6.0.5 on 2026-05-11 08:15

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_rename_created_at_expense_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.expense_receipt_upload_path),
        ),
    ]
