# Generated by Django 6.0.5 on 2026-05-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_expense_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
