# Generated by Django 5.2.13 on 2026-05-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_remove_employee_blood_group_employee_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
