# Generated by Django 6.0.4 on 2026-05-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_expense_receipt_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='offboarding',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='offboarding/'),
        ),
    ]
