# Generated by Django 6.0.4 on 2026-05-19 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_offboarding_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('Leave', 'Leave'), ('WFH', 'WFH'), ('Holiday', 'Holiday'), ('Meeting', 'Meeting'), ('Shift', 'Shift'), ('Task Deadline', 'Task Deadline'), ('Attendance Issue', 'Attendance Issue'), ('Training', 'Training'), ('Company Event', 'Company Event'), ('Late Mark', 'Late Mark'), ('Absent', 'Absent')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('visibility', models.CharField(choices=[('Private', 'Private'), ('Team', 'Team'), ('Department', 'Department'), ('Organization', 'Organization')], default='Private', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('office', models.CharField(blank=True, max_length=100, null=True)),
                ('color_code', models.CharField(default='#3b82f6', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_planner_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_planner_events', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planner_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlannerHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('holiday_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('color_code', models.CharField(default='#10b981', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlannerShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('color_code', models.CharField(default='#f59e0b', max_length=20)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shifts', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_shifts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
