# Generated by Django 5.2.13 on 2026-05-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportquery',
            name='recipient_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportquery',
            name='sender_read',
            field=models.BooleanField(default=True),
        ),
    ]
