# Generated by Django 5.2.13 on 2026-05-12 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_supportquery_recipient_read_supportquery_sender_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='casual_leaves',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sick_leaves',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vacation_leaves',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('employee', 'Employee'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
