# Generated by Django 6.0.5 on 2026-05-20 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_plannerevent_plannerholiday_plannershift'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('scope', models.CharField(default='Global', max_length=50)),
                ('department', models.CharField(blank=True, choices=[('Management', 'Management'), ('Development', 'Development'), ('HR', 'HR'), ('Finance', 'Finance'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Operations', 'Operations')], max_length=100, null=True)),
                ('office', models.CharField(blank=True, choices=[('Headquarters', 'Headquarters'), ('New York', 'New York'), ('Chicago', 'Chicago'), ('San Francisco', 'San Francisco'), ('London', 'London'), ('Remote', 'Remote')], max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='plannerevent',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plannershift',
            name='recurring_pattern',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='plannershift',
            name='rotation_cycle_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='plannershift',
            name='rotation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='feed_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='plannerevent',
            index=models.Index(fields=['employee', 'start_date'], name='myapp_plann_employe_27c46b_idx'),
        ),
        migrations.AddIndex(
            model_name='plannerevent',
            index=models.Index(fields=['status', 'start_date'], name='myapp_plann_status_a92f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='plannerevent',
            index=models.Index(fields=['is_approved', 'start_date'], name='myapp_plann_is_appr_7b57e3_idx'),
        ),
        migrations.AddField(
            model_name='plannerlock',
            name='affected_employees',
            field=models.ManyToManyField(blank=True, related_name='affected_locks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plannerlock',
            name='locked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locked_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plannerlock',
            name='unlocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='plannerlock',
            index=models.Index(fields=['start_date'], name='myapp_plann_start_d_542f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='plannerlock',
            index=models.Index(fields=['end_date'], name='myapp_plann_end_dat_a3e5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='plannerlock',
            index=models.Index(fields=['scope'], name='myapp_plann_scope_86a14f_idx'),
        ),
        migrations.AddIndex(
            model_name='plannerlock',
            index=models.Index(fields=['is_active'], name='myapp_plann_is_acti_0a7c01_idx'),
        ),
    ]
