# Generated by Django 5.2.13 on 2026-05-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_notification_recipient_alter_employee_casual_leaves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_mode',
            field=models.CharField(default='Office', max_length=50),
        ),
    ]
