# Generated by Django 5.1.1 on 2026-05-19 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_rename_created_at_expense_submitted_at_and_more'),
        ('myapp', '0042_employee_profile_picture_employee_work_mode'),
    ]

    operations = [
    ]
