# Generated by Django 6.0.5 on 2026-05-20 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_auto_20260520_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='feed_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
