# Generated by Django 5.1.1 on 2026-05-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_offboarding_file'),
        ('myapp', '0043_merge_20260519_1102'),
    ]

    operations = [
    ]
