# Generated by Django 5.2.13 on 2026-05-19 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='myapp.company'),
        ),
    ]
