# Generated by Django 5.2.13 on 2026-05-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_company_license_expiry_date_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='paid_leaves',
            field=models.IntegerField(default=0),
        ),
    ]
