# Generated by Django 5.1.1 on 2026-05-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_employee_paid_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='payment_method',
            field=models.CharField(default='Card', max_length=50),
        ),
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(default='Success', max_length=20),
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
