# Generated by Django 5.2.13 on 2026-05-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_transactions_payment_method_transactions_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportquery',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
