# Generated by Django 5.1.1 on 2026-05-21 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_supportquery_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppreciationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appreciation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.appreciation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciation_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
