# Generated by Django 5.2.13 on 2026-05-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_employeecase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecase',
            name='employee',
        ),
        migrations.AddField(
            model_name='employeecase',
            name='employees',
            field=models.ManyToManyField(related_name='involved_cases', to='myapp.employee'),
        ),
    ]
