# Generated by Django 5.2.13 on 2026-05-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_helpdeskcategory_helpdeskticket_helpdeskreply_and_more'),
        ('myapp', '0058_company_max_users_company_subscription_plan'),
    ]

    operations = [
    ]
